[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; THIS IS THE MAGIC PART:
lib_deps =
    featherfly/SoftwareSerial @ ^1.0
    adafruit/Adafruit BNO08x @ ^1.2.5
    adafruit/Adafruit BusIO @ ^1.14.1
    arduino-libraries/Servo @ ^1.1.8